# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chauncy's Space
email: chauncyff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Chauncy's Personal Blog. #word, #code, #photography
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chauncyf
timezone: America/New_York

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-archives

sass:
  style: compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

collections:
  notes:
    output: true

defaults:
  - scope:
      path: "assets/gallery"
    values:
      gallery: true
  - scope:
      path: "assets/gallery/thumbnail"
    values:
      thumbnail: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      category:
      tags:
    posts:
      author: Chauncy
      category: blog
      tags:
      published: true

jekyll-archives:
  layout: archive
  enabled: ['year', 'tags']
  permalinks:
    tag: '/archive/tag/:name/'
    year: '/archive/year/:year/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
